# fly.toml app configuration file generated for be-portfolio-app on 2026-02-03T23:05:12+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'be-portfolio-app'
primary_region = 'sin'

[[restart]]
  policy = "never"
  retries = 0
  processes = ["app"]

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "uploads"
  destination = "/app/public/uploads"
